/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Course = IDL.Record({
  'credits' : IDL.Nat,
  'creditHours' : IDL.Nat,
  'prerequisites' : IDL.Vec(IDL.Text),
  'instructor' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'schedule' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Grade = IDL.Record({
  'studentId' : IDL.Text,
  'instructorComments' : IDL.Text,
  'assignment' : IDL.Text,
  'assignmentName' : IDL.Text,
  'date' : Time,
  'dueDate' : Time,
  'description' : IDL.Text,
  'score' : IDL.Nat,
  'submissionDate' : Time,
  'courseCode' : IDL.Text,
});
export const InstructorProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'officeHours' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'officeLocation' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Student = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'major' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'emergencyContactPhone' : IDL.Text,
  'emergencyContactName' : IDL.Text,
  'enrollmentDate' : Time,
  'phone' : IDL.Text,
  'emergencyContactRelationship' : IDL.Text,
  'program' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'graded' : IDL.Null,
  'submitted' : IDL.Null,
  'late' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'pdf' : ExternalBlob,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'studentId' : IDL.Text,
  'description' : IDL.Text,
  'grade' : IDL.Nat,
  'submissionDate' : Time,
});
export const Attendance = IDL.Record({
  'studentId' : IDL.Text,
  'sessionDate' : Time,
  'present' : IDL.Bool,
  'courseCode' : IDL.Text,
});
export const Enrollment = IDL.Record({
  'studentId' : IDL.Text,
  'enrollmentDate' : Time,
  'courseCode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([Course], [], []),
  'addGrade' : IDL.Func([Grade], [], []),
  'addInstructorProfile' : IDL.Func([InstructorProfile], [], []),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'addStudent' : IDL.Func([Student], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'deleteInstructorProfile' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'enrollStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllInstructorProfiles' : IDL.Func(
      [],
      [IDL.Vec(InstructorProfile)],
      ['query'],
    ),
  'getAllStudentGrades' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Grade)))],
      ['query'],
    ),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getInstructorProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(InstructorProfile)],
      ['query'],
    ),
  'getProjectById' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getProjectsByStudentId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getStudentAttendance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getStudentEnrollments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getStudentGrades' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Grade)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttendance' : IDL.Func([Attendance], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCourse' : IDL.Func([Course], [], []),
  'updateGrade' : IDL.Func([Grade], [], []),
  'updateInstructorProfile' : IDL.Func([InstructorProfile], [], []),
  'updateProjectGrade' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateProjectStatus' : IDL.Func([IDL.Text, ProjectStatus], [], []),
  'updateStudent' : IDL.Func([Student], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Course = IDL.Record({
    'credits' : IDL.Nat,
    'creditHours' : IDL.Nat,
    'prerequisites' : IDL.Vec(IDL.Text),
    'instructor' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'schedule' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Grade = IDL.Record({
    'studentId' : IDL.Text,
    'instructorComments' : IDL.Text,
    'assignment' : IDL.Text,
    'assignmentName' : IDL.Text,
    'date' : Time,
    'dueDate' : Time,
    'description' : IDL.Text,
    'score' : IDL.Nat,
    'submissionDate' : Time,
    'courseCode' : IDL.Text,
  });
  const InstructorProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'officeHours' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'officeLocation' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Student = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'major' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'emergencyContactPhone' : IDL.Text,
    'emergencyContactName' : IDL.Text,
    'enrollmentDate' : Time,
    'phone' : IDL.Text,
    'emergencyContactRelationship' : IDL.Text,
    'program' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'graded' : IDL.Null,
    'submitted' : IDL.Null,
    'late' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'pdf' : ExternalBlob,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'studentId' : IDL.Text,
    'description' : IDL.Text,
    'grade' : IDL.Nat,
    'submissionDate' : Time,
  });
  const Attendance = IDL.Record({
    'studentId' : IDL.Text,
    'sessionDate' : Time,
    'present' : IDL.Bool,
    'courseCode' : IDL.Text,
  });
  const Enrollment = IDL.Record({
    'studentId' : IDL.Text,
    'enrollmentDate' : Time,
    'courseCode' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([Course], [], []),
    'addGrade' : IDL.Func([Grade], [], []),
    'addInstructorProfile' : IDL.Func([InstructorProfile], [], []),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'addStudent' : IDL.Func([Student], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'deleteInstructorProfile' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'enrollStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllInstructorProfiles' : IDL.Func(
        [],
        [IDL.Vec(InstructorProfile)],
        ['query'],
      ),
    'getAllStudentGrades' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Grade)))],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getInstructorProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InstructorProfile)],
        ['query'],
      ),
    'getProjectById' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getProjectsByStudentId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getStudentAttendance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getStudentEnrollments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getStudentGrades' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Grade)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttendance' : IDL.Func([Attendance], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCourse' : IDL.Func([Course], [], []),
    'updateGrade' : IDL.Func([Grade], [], []),
    'updateInstructorProfile' : IDL.Func([InstructorProfile], [], []),
    'updateProjectGrade' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateProjectStatus' : IDL.Func([IDL.Text, ProjectStatus], [], []),
    'updateStudent' : IDL.Func([Student], [], []),
  });
};

export const init = ({ IDL }) => { return []; };