/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'studentId' : string,
  'sessionDate' : Time,
  'present' : boolean,
  'courseCode' : string,
}
export interface Course {
  'credits' : bigint,
  'creditHours' : bigint,
  'prerequisites' : Array<string>,
  'instructor' : string,
  'code' : string,
  'name' : string,
  'description' : string,
  'schedule' : string,
  'location' : string,
}
export interface Enrollment {
  'studentId' : string,
  'enrollmentDate' : Time,
  'courseCode' : string,
}
export type ExternalBlob = Uint8Array;
export interface Grade {
  'studentId' : string,
  'instructorComments' : string,
  'assignment' : string,
  'assignmentName' : string,
  'date' : Time,
  'dueDate' : Time,
  'description' : string,
  'score' : bigint,
  'submissionDate' : Time,
  'courseCode' : string,
}
export interface InstructorProfile {
  'id' : string,
  'bio' : string,
  'officeHours' : string,
  'name' : string,
  'email' : string,
  'officeLocation' : string,
  'phone' : string,
  'department' : string,
}
export interface Project {
  'id' : string,
  'pdf' : ExternalBlob,
  'status' : ProjectStatus,
  'title' : string,
  'studentId' : string,
  'description' : string,
  'grade' : bigint,
  'submissionDate' : Time,
}
export type ProjectStatus = { 'graded' : null } |
  { 'submitted' : null } |
  { 'late' : null };
export interface Student {
  'id' : string,
  'dob' : string,
  'major' : string,
  'name' : string,
  'year' : bigint,
  'email' : string,
  'address' : string,
  'emergencyContactPhone' : string,
  'emergencyContactName' : string,
  'enrollmentDate' : Time,
  'phone' : string,
  'emergencyContactRelationship' : string,
  'program' : string,
}
export type Time = bigint;
export interface UserProfile {
  'studentId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<[Course], undefined>,
  'addGrade' : ActorMethod<[Grade], undefined>,
  'addInstructorProfile' : ActorMethod<[InstructorProfile], undefined>,
  'addProject' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    undefined
  >,
  'addStudent' : ActorMethod<[Student], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'deleteInstructorProfile' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'enrollStudent' : ActorMethod<[string, string], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllInstructorProfiles' : ActorMethod<[], Array<InstructorProfile>>,
  'getAllStudentGrades' : ActorMethod<[string], Array<[string, Array<Grade>]>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getInstructorProfile' : ActorMethod<[string], [] | [InstructorProfile]>,
  'getProjectById' : ActorMethod<[string], [] | [Project]>,
  'getProjectsByStudentId' : ActorMethod<[string], Array<Project>>,
  'getStudent' : ActorMethod<[string], [] | [Student]>,
  'getStudentAttendance' : ActorMethod<[string, string], Array<Attendance>>,
  'getStudentEnrollments' : ActorMethod<[string], Array<Enrollment>>,
  'getStudentGrades' : ActorMethod<[string, string], Array<Grade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAttendance' : ActorMethod<[Attendance], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCourse' : ActorMethod<[Course], undefined>,
  'updateGrade' : ActorMethod<[Grade], undefined>,
  'updateInstructorProfile' : ActorMethod<[InstructorProfile], undefined>,
  'updateProjectGrade' : ActorMethod<[string, bigint], undefined>,
  'updateProjectStatus' : ActorMethod<[string, ProjectStatus], undefined>,
  'updateStudent' : ActorMethod<[Student], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];